# Generated by Django 3.2.1 on 2021-05-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20210511_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('empty', models.FloatField()),
                ('sadness', models.FloatField()),
                ('enthusiasm', models.FloatField()),
                ('worry', models.FloatField()),
                ('surprise', models.FloatField()),
                ('love', models.FloatField()),
                ('fun', models.FloatField()),
                ('hate', models.FloatField()),
                ('happiness', models.FloatField()),
                ('boredom', models.FloatField()),
                ('relief', models.FloatField()),
                ('anger', models.FloatField()),
            ],
        ),
    ]
