# Generated by Django 3.2.1 on 2021-05-15 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20210514_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testId', models.IntegerField()),
                ('start', models.FloatField()),
                ('end', models.FloatField()),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='useremotions',
            name='anger',
        ),
        migrations.RemoveField(
            model_name='useremotions',
            name='boredom',
        ),
        migrations.RemoveField(
            model_name='useremotions',
            name='empty',
        ),
        migrations.RemoveField(
            model_name='useremotions',
            name='enthusiasm',
        ),
        migrations.RemoveField(
            model_name='useremotions',
            name='fun',
        ),
        migrations.RemoveField(
            model_name='useremotions',
            name='relief',
        ),
        migrations.RemoveField(
            model_name='useremotions',
            name='surprise',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='photo',
        ),
        migrations.AddField(
            model_name='testresult',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='testresult',
            name='photo',
            field=models.CharField(default='defaultphoto.png', max_length=200),
        ),
        migrations.AddField(
            model_name='variant',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
