# Generated by Django 3.2.1 on 2021-05-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20210515_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
