from django.contrib import admin
from apis import models

admin.site.register(models.User)
admin.site.register(models.Diary)
admin.site.register(models.Record)
admin.site.register(models.PremiumUser)
admin.site.register(models.Psychologist)
admin.site.register(models.Consultation)
admin.site.register(models.TestResult)
admin.site.register(models.Test)
admin.site.register(models.TestHasCategories)
admin.site.register(models.Category)
admin.site.register(models.Question)
admin.site.register(models.ArticleView)
admin.site.register(models.VideoListView)
admin.site.register(models.AudioListView)
admin.site.register(models.NotificationView)
admin.site.register(models.Article)
admin.site.register(models.Notification)
admin.site.register(models.VideoList)
admin.site.register(models.AudioList)
admin.site.register(models.Video)
admin.site.register(models.Audio)
admin.site.register(models.VideoHasVideoList)
admin.site.register(models.AudioHasAudioList)
admin.site.register(models.UserEmotions)
admin.site.register(models.Score)
admin.site.register(models.Variant)